name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check PR title format
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        if [[ ! "$PR_TITLE" =~ ^(feat|fix|docs|style|refactor|test|chore|clean)(\(.+\))?: ]]; then
          echo "❌ PR title must follow Conventional Commits format"
          echo "Examples: feat: add new feature, fix: resolve bug, docs: update readme"
          exit 1
        fi
        echo "✅ PR title format is valid"
    
    - name: Check for required PR template sections
      run: |
        PR_BODY="${{ github.event.pull_request.body }}"
        
        # Check for required sections
        if [[ ! "$PR_BODY" =~ "## 概要" ]]; then
          echo "❌ PR body must include '## 概要' section"
          exit 1
        fi
        
        if [[ ! "$PR_BODY" =~ "## 変更種別" ]]; then
          echo "❌ PR body must include '## 変更種別' section"
          exit 1
        fi
        
        if [[ ! "$PR_BODY" =~ "## 変更内容" ]]; then
          echo "❌ PR body must include '## 変更内容' section"
          exit 1
        fi
        
        echo "✅ PR template sections are present"

  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Check file count in PR
      run: |
        FILES_CHANGED=$(git diff --name-only origin/main...HEAD | wc -l)
        echo "Files changed: $FILES_CHANGED"
        
        if [ "$FILES_CHANGED" -gt 10 ]; then
          echo "⚠️ Warning: PR changes more than 10 files ($FILES_CHANGED files)"
          echo "Consider breaking this into smaller PRs for easier review"
        else
          echo "✅ File count is reasonable"
        fi
        
    - name: Check diff size
      run: |
        DIFF_SIZE=$(git diff --stat origin/main...HEAD | tail -n 1 | grep -o '[0-9]\+ insertions\|[0-9]\+ deletions' | grep -o '[0-9]\+' | paste -sd+ | bc || echo "0")
        echo "Diff size: $DIFF_SIZE lines"
        
        if [ "$DIFF_SIZE" -gt 400 ]; then
          echo "⚠️ Warning: PR has large diff ($DIFF_SIZE lines)"
          echo "Consider breaking this into smaller PRs for easier review"
        else
          echo "✅ Diff size is reasonable"
        fi

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Scan for secrets
      run: |
        # Basic secret pattern detection
        echo "🔍 Scanning for potential secrets..."
        
        # Check for common secret patterns
        if grep -r -i "password\s*=\s*['\"][^'\"]*['\"]" . --exclude-dir=.git --exclude-dir=node_modules; then
          echo "❌ Potential hardcoded password found"
          exit 1
        fi
        
        if grep -r -i "api[_-]key\s*=\s*['\"][^'\"]*['\"]" . --exclude-dir=.git --exclude-dir=node_modules; then
          echo "❌ Potential API key found"
          exit 1
        fi
        
        if grep -r -i "secret\s*=\s*['\"][^'\"]*['\"]" . --exclude-dir=.git --exclude-dir=node_modules; then
          echo "❌ Potential secret found"
          exit 1
        fi
        
        echo "✅ No obvious secrets detected"